//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrammatikLaxen.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class substantiv
    {
        public int Id { get; set; }
        public string ord { get; set; }
        public string ordklass { get; set; }
        public Nullable<bool> ren { get; set; }
        public string även { get; set; }
        public string betydelse { get; set; }
        public Nullable<bool> konkret { get; set; }
        public Nullable<bool> abstrakt { get; set; }
        public string genus { get; set; }
        public string nominativ { get; set; }
        public string artikel { get; set; }
        public string obestämd_form_singular { get; set; }
        public string obestämd_form_singular_genitiv { get; set; }
        public string bestämd_form_singular { get; set; }
        public string bestämd_form_singular_genitiv { get; set; }
        public string obestämd_form_plural { get; set; }
        public string obestämd_form_plural_genitiv { get; set; }
        public string bestämd_form_plural { get; set; }
        public string bestämd_form_plural_genitiv { get; set; }
        public string bestämd_fristående_artikel_singular { get; set; }
        public string bestämd_fristående_artikel_plural { get; set; }
        public Nullable<int> fkordklass { get; set; }
    
        public virtual ordklasser ordklasser { get; set; }
    }
}
