//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrammatikLaxen.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class toppresultat
    {
        public int Id { get; set; }
        public Nullable<int> resultat { get; set; }
        public string initialer { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
    }
}
