//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrammatikLaxen
{
    using System;
    using System.Collections.Generic;
    
    public partial class adverb
    {
        public int Id { get; set; }
        public string ord { get; set; }
        public string ordklass { get; set; }
        public string ordklass_2 { get; set; }
        public Nullable<bool> ren { get; set; }
        public string typ { get; set; }
        public string typ_2 { get; set; }
        public string typ_3 { get; set; }
        public string typ_4 { get; set; }
        public string typ_5 { get; set; }
        public string typ_6 { get; set; }
        public string typ_7 { get; set; }
        public string typ_8 { get; set; }
        public string typ_9 { get; set; }
        public Nullable<bool> tidsadverb { get; set; }
        public Nullable<bool> rumsadverb { get; set; }
        public Nullable<bool> sättsadverb { get; set; }
        public Nullable<bool> gradadverb { get; set; }
        public Nullable<bool> orsaksadverb { get; set; }
        public Nullable<bool> relativa_adverb { get; set; }
        public Nullable<bool> satsadverb { get; set; }
        public Nullable<int> fkordklass { get; set; }
    
        public virtual ordklasser ordklasser { get; set; }
    }
}
