//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrammatikLaxen
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gramLaDatEntities : DbContext
    {
        public gramLaDatEntities()
            : base("name=gramLaDatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adjektiv> adjektiv { get; set; }
        public virtual DbSet<adverb> adverb { get; set; }
        public virtual DbSet<interjektion> interjektion { get; set; }
        public virtual DbSet<konjunktion> konjunktion { get; set; }
        public virtual DbSet<ordklasser> ordklasser { get; set; }
        public virtual DbSet<preposition> preposition { get; set; }
        public virtual DbSet<pronomen> pronomen { get; set; }
        public virtual DbSet<räkneord> räkneord { get; set; }
        public virtual DbSet<substantiv> substantiv { get; set; }
        public virtual DbSet<toppresultat> toppresultat { get; set; }
        public virtual DbSet<verb> verb { get; set; }
    }
}
