//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrammatikLaxen
{
    using System;
    using System.Collections.Generic;
    
    public partial class pronomen
    {
        public int Id { get; set; }
        public string ord { get; set; }
        public string ordklass { get; set; }
        public Nullable<bool> ren { get; set; }
        public string även { get; set; }
        public string personliga_subjekt { get; set; }
        public string personliga_objekt { get; set; }
        public string possessiva_utrum { get; set; }
        public string possessiva_neutrum { get; set; }
        public string possessiva_plural { get; set; }
        public string reflexiva { get; set; }
        public Nullable<bool> reflexiva_possessiva { get; set; }
        public string reflexiva_possessiva_utrum { get; set; }
        public string reflexiva_possessiva_neutrum { get; set; }
        public string reflexiva_possessiva_plural { get; set; }
        public string relativa_grundform { get; set; }
        public string relativa_genitiv { get; set; }
        public string interrogativa { get; set; }
        public string interrogativa_2 { get; set; }
        public Nullable<bool> demonstrativa { get; set; }
        public string demonstrativa_nära { get; set; }
        public string demonstrativa_långt_bort { get; set; }
        public Nullable<bool> demonstrativa_2 { get; set; }
        public string demonstrativa_lika { get; set; }
        public Nullable<bool> determinativa { get; set; }
        public string determinativa_fria { get; set; }
        public string determinativa_tillsammans_med_substantiv { get; set; }
        public Nullable<bool> indefinita { get; set; }
        public string indefinita_subjekt { get; set; }
        public string indefinita_objekt { get; set; }
        public string indefinita_utrum { get; set; }
        public string indefinita_neutrum { get; set; }
        public string indefinita_plural { get; set; }
        public Nullable<int> fkordklass { get; set; }
    
        public virtual ordklasser ordklasser { get; set; }
    }
}
