//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrammatikLaxen
{
    using System;
    using System.Collections.Generic;
    
    public partial class verb
    {
        public int Id { get; set; }
        public string ord { get; set; }
        public string ordklass { get; set; }
        public Nullable<bool> ren { get; set; }
        public string även { get; set; }
        public string typ { get; set; }
        public Nullable<bool> bindeverb { get; set; }
        public Nullable<bool> hjälpverb { get; set; }
        public Nullable<bool> huvudverb { get; set; }
        public string attribut_infinitiv { get; set; }
        public string infinitiv { get; set; }
        public string attribut_preteritum { get; set; }
        public string preteritum { get; set; }
        public string attribut_supinum { get; set; }
        public string supinum { get; set; }
        public string presens { get; set; }
        public string perfekt { get; set; }
        public string pluskvamperfekt { get; set; }
        public string futurum { get; set; }
        public string imperativ { get; set; }
        public Nullable<bool> particip { get; set; }
        public string presens_particip { get; set; }
        public string presens_particip_2 { get; set; }
        public string perfekt_particip { get; set; }
        public Nullable<int> fkordklass { get; set; }
    
        public virtual ordklasser ordklasser { get; set; }
    }
}
